### ISSUE TITLE
Feature - USB and Bluetooth

### ISSUE THREAD

**Issue by thenineties** [mrtungdev/flutter_epson_epos#2]
Hi Developer. 

Good work. Having a usb and bluetooth connectivity is a great thing. Looking ahead. Thanks

**Comment by brasizza** [comment]
#6 its here!

**Comment by tegarnugroho** [comment]
feature with bluetooth not available? @mrtungdev @brasizza

**Comment by brasizza** [comment]
There is in my repository I didn't made a PR because i had to do some break changes in the connection methods, but you can use in my github to check if it's enough for you 
[repository](https://github.com/brasizza/flutter_epson_epos)

**Comment by schube** [comment]
Hi! Thanks for flutter_epson_epos and your bluetooth extension. Any chance you can create a PR and merge it with the main project? That would be very helpful! Thank you!

**Comment by brasizza** [comment]
If @mrtungdev  allows me, i can fork again his version and put in his version.

**Comment by Mohamed-Gibreel** [comment]
@brasizza I am facing an issue with the Bluetooth functionality, whenever I press on Discovery Bluetooth I get an error saying the following:
`
E/onDiscoveryPrinter( 7178): Start not working onDiscovery
W/System.err( 7178): com.epson.epos2.Epos2Exception
W/System.err( 7178):  at com.epson.epos2.discovery.Discovery.start(Discovery.java:220)
W/System.err( 7178):  at com.tlt.epson_epos.EpsonEposPlugin.onDiscoveryPrinter(EpsonEposPlugin.kt:223)
W/System.err( 7178):  at com.tlt.epson_epos.EpsonEposPlugin.onDiscovery(EpsonEposPlugin.kt:199)
W/System.err( 7178):  at com.tlt.epson_epos.EpsonEposPlugin.access$onDiscovery(EpsonEposPlugin.kt:62)
W/System.err( 7178):  at com.tlt.epson_epos.EpsonEposPlugin$MethodRunner.run(EpsonEposPlugin.kt:129)
W/System.err( 7178):  at java.lang.Thread.run(Thread.java:1012)
`

Please any help would be highly appreciated, I not really familiar with Kotlin.

**Comment by brasizza** [comment]
> @brasizza I am facing an issue with the Bluetooth functionality, whenever I press on Discovery Bluetooth I get an error saying the following: `E/onDiscoveryPrinter( 7178): Start not working onDiscovery W/System.err( 7178): com.epson.epos2.Epos2Exception W/System.err( 7178): at com.epson.epos2.discovery.Discovery.start(Discovery.java:220) W/System.err( 7178): at com.tlt.epson_epos.EpsonEposPlugin.onDiscoveryPrinter(EpsonEposPlugin.kt:223) W/System.err( 7178): at com.tlt.epson_epos.EpsonEposPlugin.onDiscovery(EpsonEposPlugin.kt:199) W/System.err( 7178): at com.tlt.epson_epos.EpsonEposPlugin.access$onDiscovery(EpsonEposPlugin.kt:62) W/System.err( 7178): at com.tlt.epson_epos.EpsonEposPlugin$MethodRunner.run(EpsonEposPlugin.kt:129) W/System.err( 7178): at java.lang.Thread.run(Thread.java:1012)`
> 
> Please any help would be highly appreciated, I not really familiar with Kotlin.

i think he didnt implement that featute, the 199 is the exception "not implemented"

you can try to use my fork that is bluetooth implemented to test!


https://github.com/brasizza/flutter_epson_epos

**Comment by Mohamed-Gibreel** [comment]
@brasizza I was using your repository :) But it turned out it was a mistake from my end, the application requires Nearby Location permission which is not visible in the settings until you start the application and start searching for the printer via Bluetooth. For anyone facing this issue, please do the following:

1. Start the example application.
2. Click on search by Bluetooth
3. If it doesn't work, go to the app settings from your phone and enable all 3 permissions ( Location, Nearby Devices & Storage ).
4. Try again. 

This is what worked for me. I am not sure if storage permission is required but I enabled it just incase.

The phone I am using is Oneplus 7T Pro.

Again, @brasizza thank you for your work. It is much appreciated.

**Comment by karthik-payzli** [comment]
Hi can u add funtionality for TM-m30III printers

**Comment by karthik-payzli** [comment]
I'm using TM-m30III thermal printer but it detecting it as TM_T20 printer can u fix this if possible

**Comment by karthik-payzli** [comment]
HI there, I'm using Tm-m30III thermal printer but while finding the device in function OnDiscovery through usb it showing different serial and model how to fix this

**Comment by karthik-payzli** [comment]
HI there, I'm using Tm-m30III thermal printer but while finding the device in function OnDiscovery through usb it showing different serial and model how to fix this when I try to print test its not working .
